tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "primary-fixed": "#ffdbd1",
                "on-primary-container": "#6d1a00",
                "on-secondary-fixed-variant": "#284968",
                "primary-container": "#ff7b54",
                "on-secondary-fixed": "#001d33",
                "inverse-primary": "#ffb5a0",
                "error-container": "#ffdad6",
                "tertiary-container": "#00b4b2",
                "on-primary-fixed-variant": "#862302",
                "surface": "#FDFDFD",
                "on-tertiary-fixed": "#00201f",
                "surface-container-highest": "#e2e2e2",
                "background": "#FDFDFD",
                "surface-container-low": "#f3f3f3",
                "on-primary": "#ffffff",
                "primary": "#a63a19",
                "inverse-on-surface": "#f0f1f1",
                "tertiary": "#006a68",
                "surface-container-high": "#e8e8e8",
                "surface-tint": "#a63a19",
                "outline": "#8b716a",
                "surface-variant": "#e2e2e2",
                "on-primary-fixed": "#3b0a00",
                "surface-bright": "#f9f9f9",
                "error": "#ba1a1a",
                "on-surface": "#1a1c1c",
                "surface-dim": "#dadada",
                "on-tertiary-fixed-variant": "#00504f",
                "secondary-fixed": "#cfe5ff",
                "primary-fixed-dim": "#ffb5a0",
                "outline-variant": "#dfc0b7",
                "surface-container-lowest": "#ffffff",
                "surface-container": "#eeeeee",
                "tertiary-fixed-dim": "#4edad8",
                "tertiary-fixed": "#70f7f4",
                "on-secondary-container": "#40607f",
                "on-error": "#ffffff",
                "secondary-fixed-dim": "#a9caee",
                "secondary": "#416181",
                "on-error-container": "#93000a",
                "on-background": "#1a1c1c",
                "on-tertiary-container": "#003f3f",
                "secondary-container": "#badaff",
                "on-surface-variant": "#58423c",
                "on-secondary": "#ffffff",
                "inverse-surface": "#2f3131",
                "on-tertiary": "#ffffff"
            },
            fontFamily: {
                "headline": ["Noto Serif SC", "serif"],
                "display": ["Playfair Display", "serif"],
                "body": ["Work Sans", "sans-serif"],
                "label": ["Work Sans", "sans-serif"]
            },
            fontSize: {
                "fluid-sm": "clamp(0.875rem, 0.8rem + 0.38vw, 1.125rem)",
                "fluid-base": "clamp(1rem, 0.925rem + 0.38vw, 1.25rem)",
                "fluid-lg": "clamp(1.125rem, 1rem + 0.63vw, 1.5rem)",
                "fluid-xl": "clamp(1.25rem, 1.05rem + 1vw, 2rem)",
                "fluid-2xl": "clamp(1.5rem, 1.2rem + 1.5vw, 2.5rem)",
                "fluid-3xl": "clamp(1.75rem, 1.25rem + 2.5vw, 3.5rem)",
                "fluid-4xl": "clamp(2rem, 1.25rem + 3.75vw, 4.5rem)",
                "fluid-5xl": "clamp(2.5rem, 1.5rem + 5vw, 6rem)",
                "fluid-6xl": "clamp(3rem, 1.5rem + 7.5vw, 8rem)",
            },
            spacing: {
                "fluid-sm": "clamp(0.5rem, 0.3rem + 1vw, 1rem)",
                "fluid-md": "clamp(1rem, 0.6rem + 2vw, 2rem)",
                "fluid-lg": "clamp(1.5rem, 0.5rem + 5vw, 4rem)",
                "fluid-xl": "clamp(2rem, 0.5rem + 7.5vw, 6rem)",
                "fluid-2xl": "clamp(3rem, 1rem + 10vw, 8rem)",
            },
            borderRadius: {
                "DEFAULT": "0.125rem",
                "sm": "0.125rem",
                "md": "0.25rem",
                "lg": "0.25rem",
                "xl": "0.5rem",
                "full": "0.75rem"
            },
        },
    },
};
